# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'secret-santa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for secret-santa
  pod 'Parse'
  pod 'ImageKitIO'

  target 'secret-santaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'secret-santaUITests' do
    # Pods for testing
  end

end
